enum {
    OP_TYPE_NONE = 0,
    OP_TYPE_GREATER,
    OP_TYPE_LESSER,
    OP_TYPE_PLUS,
    OP_TYPE_MINUS,
    OP_TYPE_STAR,
    OP_TYPE_DIV,
    OP_TYPE_EQUAL,
    OP_TYPE_NEQUAL
};

enum{
    VAR_TYPE_NONE = 1,
    VAR_TYPE_INT,
    VAR_TYPE_FUNCTION,
    VAR_TYPE_POINTER
};